### ISSUE TITLE
xia2.to_shelx: Incorrect wavelength exported

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#1]
User feedback 23/11/15:
xia2.to_shelx exports the incorrect wavelength

**Comment by graeme-winter** [comment]
Yes, fixing this could be subtly more complex though (I use cctbx code to generate INS file)

+ unit cell errors needed 
+ p4p file for small molecule people

**Comment by Anthchirp** [comment]
resolved now. unit cell errors available via xia2.get_unit_cell_errors. p4p file is a separate issue.
