### ISSUE TITLE
Settings in xia2 -dials for CCD detectors

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#107]
From Melanie:

I have been running Xia2 on my collection of test data, 539 PDB entries comprising MAD, SAD and native data. Of these data sets 121 resulted in failures of different kinds.

Attached is a tar file containing xia2.txt files for the failed PDB entries grouped based on the error that occurred.

For more details please look into /dls/tmp/ghp45345/xia2_stresstest/20170214/%s   %PDB-ID

The biggest number of errors occurred for "missing_file_for_indexing" (67). This seems to be an indexing problem connected with the images being collected on CCD cameras and then Xia2 not using appropriate settings for "Global Threshold" in DIALS (a value of 20 seems to be a good guess after manual inspection of a randomly chosen data set with this error). As a result background scattering in the beamstop area gets included and indexing fails.

Some of the data sets seem to be interleaved or inverse beam collections from US synchrotrons and cause Pointless and Ctruncate errors.

Getting better settings for CCD cameras during indexing would solve my biggest problem.

**Comment by graeme-winter** [comment]
Proposal here is to (i) gather a set of sensible CCD detector based defaults to pass to dials for spot finding etc then (ii) figure out a way of adding these settings to xia2 in a relatively flexible way (i.e. through dxtbx would be neat)

**Comment by rjgildea** [comment]
This is as much a dials issue as a xia2 issue in reality. As I pointed out, there is already (for a long time) the xia2 parameter dials.find_spots.global_threshold=auto which could in theory be set as the default - it just needs someone to test whether it makes sense across a wide range of datasets.

**Comment by graeme-winter** [comment]
OK, we should test this first, good point

**Comment by dagewa** [comment]
Melanie did that test

> 1)
> xia2 pipeline=dials /dls/metrix/metrix/MR_data/<PDB_ID> dials.find_spots.global_threshold=20
> total:                             754
> CCD failure:                     41
> photon-counting failure:    32
> 
> 
> 2)
> xia2 pipeline=dials /dls/metrix/metrix/MR_data/<PDB_ID>
> total:                             752
> CCD failure:                     74
> photon-counting failure:    38
> 
> 
> 3)
> xia2 pipeline=dials /dls/metrix/metrix/MR_data/<PDB_ID> dials.find_spots.global_threshold=Auto
> total:                             776
> CCD failure:                    43
> photon-counting failure:   38
> 
> Feel free to interpret the results as you wish... in any case I think either dials.find_spots.global_threshold=20 or
> dials.find_spots.global_threshold=Auto should be default in DIALS...

Strange that `global_threshold=Auto` gives more PAD failures than `global_threshold=20`. Not entirely clear what 'failure' means. Anyway, `global_threshold=Auto` seems better than the default of zero.
