### ISSUE TITLE
xia2.report disagrees with ctruncate for <I^2> plot

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#108]
<img width="601" alt="screen shot 2017-03-14 at 09 05 21" src="https://cloud.githubusercontent.com/assets/1241716/23893201/7dfb1356-0895-11e7-9bbb-d9a70bc5525c.png">
<img width="484" alt="screen shot 2017-03-14 at 09 05 26" src="https://cloud.githubusercontent.com/assets/1241716/23893202/819ee276-0895-11e7-99da-ae2827351534.png">

**Comment by graeme-winter** [comment]
So... would be really nice to work out why the two different analysis methods come out with different plots of the same value. Also find that XDS and ctruncate disagree.... and disagree with this above as well...

**Comment by rjgildea** [comment]
What do XDS plots look like?

**Comment by rjgildea** [comment]
This is the implementation of the cctbx.miller.array calculation that xia2.report is using:
https://github.com/cctbx/cctbx_project/blob/98567dde2ac6c6326057e074f5124858cfbf2a0c/cctbx/miller/__init__.py#L3065

```
  def second_moment(self, use_binning=False):
    """<data^2>/(<data>)^2"""
    assert not use_binning or self.binner() is not None
    if (not use_binning):
      if (self.indices().size() == 0): return None
      mean_data_sq = flex.mean(self.data())**2
      if (mean_data_sq == 0): return None
      return flex.mean_sq(self.data()) / mean_data_sq
    result = []
    for i_bin in self.binner().range_all():
      sel = self.binner().selection(i_bin)
      result.append(self.select(sel).second_moment())
    return binned_data(binner=self.binner(), data=result, data_fmt="%7.4f")
```

**Comment by graeme-winter** [comment]
Much better now using merged data though not identical... however that may be binning weirdness or something. This change above makes a massive enough difference I will close this now.
