### ISSUE TITLE
small molecule: if low and high angle sweeps do not overlap pointless now crashes

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#115]
This did not used to happen I think, but now means that we cannot process high angle (i.e. 2-theta > 60 degrees) data; get 

```
Status: error "Pointless error: Resolution range of Reference data and observed data do not overlap"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```

via

```
**** ERROR ****
Resolution range of Reference data and observed data do not overlap

<!--SUMMARY_BEGIN-->
<B><FONT COLOR="#FF8800">
<!--SUMMARY_END-->
--------------------------------------------------------------------

FATAL ERROR message: 
Resolution range of Reference data and observed data do not overlap
--------------------------------------------------------------------
<!--SUMMARY_BEGIN-->
</FONT></B>
<!--SUMMARY_END-->
```

**Comment by graeme-winter** [comment]
TBH we have already indexed these all at once already by this stage => should just ignore this?

**Comment by Anthchirp** [comment]
Only true for multisweep indexing?

**Comment by graeme-winter** [comment]
Yes, if multisweep indexing we should be able to ignore...

**Comment by graeme-winter** [comment]
@Anthchirp we should add a test to the regression system which pushes something like this, so we do not get caught out in the future. @rjgildea we should probably try to work out a way to bootstrap the orientation standardisation i.e. work out which sets have a decent overlap, computing the tree of sweeps with the most overlap then using this to work out the common orientation rather than selecting one reference. This would also fix the same shaped problem for in situ data collection i.e. something like the Brehm Diederichs algorithm. Guess this would be a xia2 0.6 feature.

**Comment by graeme-winter** [comment]
Fix above is incomplete - pointgroup coming out as empty string from $somewhere

**Comment by graeme-winter** [comment]
Other non-fatal errors may be raised which later turn out to be fatal, debugging at the moment (mortally wounded error?)

**Comment by graeme-winter** [comment]
@Anthchirp in here are cherries for 1.6

**Comment by graeme-winter** [comment]
N.B. for this kind of data pipeline=3dii likely to fail
