### ISSUE TITLE
xia2 pipeline=2d

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#120]
do we have tests? is this expected to work?

**Comment by Anthchirp** [comment]
Q1: Not that I am aware, we run dials and 3di with ccp4a scaler

**Comment by graeme-winter** [comment]
OK, we should probably add one with CCD data (will do)

**Comment by graeme-winter** [comment]
Testing this now

**Comment by graeme-winter** [comment]
xia2 pipeline=2d ~/svn/cctbx/build/xia2_regression/test_data/insulin/

This worked so pipeline not obviously broken

**Comment by graeme-winter** [comment]
Test added, closing ticket
