### ISSUE TITLE
Xia2 stuck in the Integration step

### ISSUE THREAD

**Issue by aspunekar** [xia2/xia2#127]
I am running Xia2 using pipeline 3d. In the command line, I am giving the space group and cell dimensions as well. In the Autoindexing step, Xia2 finds the correct indexing solution, but then gets stuck in the Integrating step. It keeps on building the .tmp files in the integrate folder and never finishes. Please help me to solve this issue.

**Comment by Anthchirp** [comment]
could you attach a copy of xia2.txt and xia2-debug.txt or, if you don't want them shared publically, send them to xia2.support@gmail.com?

**Comment by Anthchirp** [comment]
From the xia2.txt I can see you use the xia2 version distributed with phenix. That is now 8 months old. Could you try running the current version, distributed with [DIALS 1.6](http://dials.github.io/installation.html)?
I can't see a particular reason why XDS would get stuck on this. How long did you wait for it to finish?
Have you tried the DIALS pipeline (run xia2 without the pipeline= parameter)?

**Comment by Anthchirp** [comment]
Forgot the obvious..: Did you check the XDS log file? The location of that is given in the last line of xia2-debug.txt

**Comment by aspunekar** [comment]
Thank you Markus for the quick check. I didn't realise that I am using Xia2 from Phenix. I will switch to CCP4 as it has the most recent Xia2. Yes, will look into the XDS log file. Thanks.

**Comment by aspunekar** [comment]
Sorry forgot to tell you. XDS is integrating for last 2 hours and hasn't yet finished.

**Comment by Anthchirp** [comment]
I'm afraid without the XDS logs we can't do anything more at this point.
It may be worth contacting XDS support about this as it sounds like an XDS issue in any case, and I suspect we would not be able to do much about this in xia2.
