### ISSUE TITLE
dispatcher messing with LD_LIBRARY_PATH kills blend

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#132]
```
export LD_LIBRARY_PATH="$BUILD_PATH/lib:$BUILD_PATH/../base/lib:/$BUILD_PATH/lib:/$BUILD_PATH/../base/lib"
R -q -e "png('foo.png')"
```
crashes.

We are already touching LD_LIBRARY_PATH in [Decorators/CCP4Decorator.py](https://github.com/xia2/xia2/blob/master/Decorators/CCP4Decorator.py#L90) and [Driver/QSubDriver.py](https://github.com/xia2/xia2/blob/master/Driver/QSubDriver.py#L127).
Need to make sure that any fix for this will still work in CCP4 distribution.

**Comment by Anthchirp** [comment]
works on local RHEL6 machines, but apparently crashes on Ubuntu

**Comment by graeme-winter** [comment]
Do we have any method to test Ubuntu?

**Comment by dagewa** [comment]
There was a plan to do builds and tests on Ubuntu using dls-hudson@brno.rc-harwell.ac.uk

**Comment by dagewa** [comment]
Refreshing this, as it is still a thing
