### ISSUE TITLE
Improvement proposals to xia2.html with embedded report

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#133]
Completeness vs. resolution: fix scale on vertical axis to [0,1]

![newplot 19](https://user-images.githubusercontent.com/1241716/27318219-2c7d826c-5583-11e7-9345-d8e9a7e2f77e.png)

**Comment by graeme-winter** [comment]
Wilson intensity plot: resolution range does not match overall range of data set:

![newplot 20](https://user-images.githubusercontent.com/1241716/27318239-4cb06af4-5583-11e7-8619-e6d394d5d1ac.png)

Also, having micro / pico prefix then switch to scientific notation is odd :)

**Comment by graeme-winter** [comment]
(this is small molecule; centric data && 0.5A resolution so obvious I guess...)

**Comment by rjgildea** [comment]
As far as I can tell the wilson plot resolution range should match the resolution range of the dataset. Care to share how I can reproduce the above plots?

**Comment by graeme-winter** [comment]
xia2.small_molecule  /dls/i19-1/data/2017/nr18193-1/35dnba_30K_2_28mm ;
open *html

**Comment by rjgildea** [comment]
Do you have the scaled/unmerged mtz somewhere handy to save me having to re-run the entire processing?

**Comment by rjgildea** [comment]
This is small molecule/high resolution xtriage thing:

https://github.com/cctbx/cctbx_project/blob/master/mmtbx/scaling/data_statistics.py#L1014

```
    # First we have to apply a resolution cut to make sure the reslution limts
    # match those of the empirical gamma array
    absolute_miller = miller_array.resolution_filter(
      d_max = math.sqrt(1.0/0.008),
      d_min = math.sqrt(1.0/0.69))
```

**Comment by rjgildea** [comment]
The code that calculates the expected wilson intensity distribution assumes typical protein, not sure how applicable this is to general small molecule data anyway:
https://github.com/cctbx/cctbx_project/blob/master/mmtbx/scaling/absolute_scaling.py#L332
https://github.com/cctbx/cctbx_project/blob/master/mmtbx/scaling/absolute_scaling.py#L20

**Comment by rjgildea** [comment]
This is essentially part of https://github.com/xia2/xia2/issues/129 so tempted to close this ticket.

**Comment by graeme-winter** [comment]
[x133.zip](https://github.com/xia2/xia2/files/1089658/x133.zip)

**Comment by graeme-winter** [comment]
OK, can close this one - completeness graph improvement went through :)
