### ISSUE TITLE
multiplicities files in $cwd

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#140]
I see files such as

> 34_xia2.plot_multiplicity.log
> 35_xia2.plot_multiplicity.log
> 36_xia2.plot_multiplicity.log
> multiplicities_h_0.json
> multiplicities_h_0.png
> multiplicities_k_0.json
> multiplicities_k_0.png
> multiplicities_l_0.json
> multiplicities_l_0.png

appear in the working directory on an I19 visit. Should these be moved somewhere else?

**Comment by rjgildea** [comment]
This is because xia2.html runs in the current working directory. Feel free to make it run in $othercwd to make these files go some place else.
