### ISSUE TITLE
Green boxes in HTML report gone

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#141]
Quote:
> If this feature were to exist [again] that would be nice

**Comment by rjgildea** [comment]
@graeme-winter said they weren't really necessary. I don't think they really show anything that isn't in the various plots that are now included in the html report.

**Comment by graeme-winter** [comment]
@rjgildea is entirely correct however if users like them should we reinstate this $somewhere; #discuss

**Comment by rjgildea** [comment]
What information do they show that isn't obtainable through the various plots now included? Perhaps said users haven't discovered the plots that are now there?

**Comment by rjgildea** [comment]
The "green boxes" were essentially some kind of weird plot of I/sigI vs batch. We currently have a plot of I/sigI vs batch in the new html report (only I/sigI vs resolution), but it should be easy to add such a plot.

**Comment by rjgildea** [comment]
Plot of I/sigI vs batch now in xia2.html report:
<img width="515" alt="screen shot 2017-06-22 at 10 20 09" src="https://user-images.githubusercontent.com/2810624/27441914-784b596e-5734-11e7-9734-cb34dac04807.png">

**Comment by graeme-winter** [comment]
Consensus with this one was that this is enough information for the moment? Can recover the "little green boxes" from the text if needed...
