### ISSUE TITLE
build instructions (SConstruct file?)

### ISSUE THREAD

**Issue by pameyer** [xia2/xia2#144]
Would it be possible to add a little info for how to build xia2 from source?  From the `SConscript` file it looks like it's using scons; but there doesn't seem to be a SConstruct file in the repository.

**Comment by rjgildea** [comment]
See here for installation instructions for release and nightly builds: http://dials.github.io/installation.html
or for building from source:
http://dials.github.io/documentation/installation_developer.html

**Comment by pameyer** [comment]
thanks @rjgildea
