### ISSUE TITLE
xia2.html: exclude certain aspects in small molecule mode

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#150]
Certain aspects of xia2.html currently less relevant for small molecules, e.g. xtriage output, Rd analysis.

**Comment by Anthchirp** [comment]
Would add PHIL params for individual bits and then change these when small_molecule is set

**Comment by graeme-winter** [comment]
If excluding RD plot, chef analysis also probably not relevant, nor completeness vs. dose etc... particularly for > 1 two-theta position
