### ISSUE TITLE
xia2 pipeline=3d gives error "indexing failed"

### ISSUE THREAD

**Issue by aspunekar** [xia2/xia2#157]
Hi, I have a 3.0Å data set. When I process the data using xia2 pipeline=3d, I get Status: error "indexing failed". However, when I process the same data directly in XDS, it works smoothly and XDS doesn't complain about the data set. So, why I am getting this error "indexing failed" when I use XDS through xia2? I have attached the xia2-debug.txt, xia2.txt and xia2.error files. Please help.

[xia2-debug.txt](https://github.com/xia2/xia2/files/1141408/xia2-debug.txt)
[xia2.txt](https://github.com/xia2/xia2/files/1141407/xia2.txt)
[xia2_error.txt](https://github.com/xia2/xia2/files/1141412/xia2_error.txt)

**Comment by graeme-winter** [comment]
Have you tried with pipeline=3dii? In many cases this is more reliable and probably a closer map to your own use of XDS

**Comment by aspunekar** [comment]
Hi Graeme, pipeline=3dii did work. Thank you for your help.
