### ISSUE TITLE
Replace sortmtz with CCTBX Python jiffy

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#165]
This could be more complicated as this is potentially expensive... the MTZ file _may_ be too big to fit in RAM

**Comment by rjgildea** [comment]
Is this sortmtz step actually necessary? I recall Phil Evans saying:
> (Incidentally, I had some trouble tracing the elaborate procedure in the XIa2scale directory, but I note a sortmtz step which I’m sure is unnecessary)

**Comment by graeme-winter** [comment]
Hmm possibly not; testing this conceptually would be useful

Though: sortmtz is also used as the here-we-join-mtz-files tool for multi-sweep data sets (and multi-wavelength)
