### ISSUE TITLE
Completeness in .html vs AUTOMATIC_DEFAULT_NATIVE_merging-statistics.txt and xia2.txt

### ISSUE THREAD

**Issue by lksaunders** [xia2/xia2#170]
In xia2 small_molecule:

The overall completeness reported in xia2.html does not match that reported in AUTOMATIC_DEFAULT_NATIVE_merging-statistics.txt and xia2.txt

 xia2.html
![xia2_html](https://user-images.githubusercontent.com/28982639/28820842-1041b642-76ab-11e7-99a2-cbd4b90a5b59.JPG)

AUTOMATIC_DEFAULT_NATIVE_merging-statistics.txt
![automatic_default_native_merging_statistics_txt](https://user-images.githubusercontent.com/28982639/28820851-15ad47ea-76ab-11e7-8e4b-a115db372776.JPG)

xia2.txt
![xia2_txt](https://user-images.githubusercontent.com/28982639/28820856-1a54dd44-76ab-11e7-8be7-eb7879f8da3c.JPG)

**Comment by graeme-winter** [comment]
Thanks for reporting, something not matching up right here.

**Comment by rjgildea** [comment]
The difference is down to eliminate_sys_absent=True vs False

**Comment by graeme-winter** [comment]
Should we switch that in reporting then? Keep things consistent
