### ISSUE TITLE
SADABS output from Xia2?

### ISSUE THREAD

**Issue by Jeff-Jeffty-Jeff** [xia2/xia2#183]
Possibly as a command line option to output SADABS rather than Pointless/Aimless?

**Comment by graeme-winter** [comment]
Reasonable question we have wondered in the past, however is dependent on access to sadabs - which for our testing systems could be problematic...

**Comment by Jeff-Jeffty-Jeff** [comment]
If it is not possible to incorporate, would I be right in thinking all of the relevant final integrated "AUTOMATIC_DEFAULT*.json" files will be outputted to the DataFiles folder? If so I can just re-export these using Dials and run them through sadabs. If there was an option to just automatically generate the .sad files to this directory it would be a great help (as it already generates a .p4p).
