### ISSUE TITLE
Sorting screwed up code

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#190]
See #189 for an example

Sorting imports seemed to have borken it  😞

**Comment by Anthchirp** [comment]
issue identified, problem is with isort.
https://github.com/timothycrosley/isort/issues/606

on our side: we used to import ```Pointless``` in line 22
https://github.com/xia2/xia2/blob/42374740e8cd6b9c53ba63c5a550dcad061a8ca3/Modules/Scaler/CCP4ScalerHelpers.py#L22
and then imported ```Pointless as _Pointless``` in line 238
https://github.com/xia2/xia2/blob/42374740e8cd6b9c53ba63c5a550dcad061a8ca3/Modules/Scaler/CCP4ScalerHelpers.py#L238

(One of the imports was, in fact, pointless.)

**Comment by Anthchirp** [comment]
Passed on to isort developers who haven't done anything about it (yet), so I have disabled isort instead. May re-enable it again at some point in the future.
