### ISSUE TITLE
new shelxt_a.hkl missing unit cell esds (small_molecule)

### ISSUE THREAD

**Issue by lksaunders** [xia2/xia2#192]
I have a dataset which xia2 processes with space group P21/a. Space group should be P21/c. Shelxt has done the conversion in my data directory but the new hkl (in folder 'structure') shelxt_a.hkl does not have esds for the unit cell parameters. How can I fix this/where can I get them from? I've tried reprocessing the data sets (there are actually 11 of these as VT data) using the space_group fix. This gives the correct space group, P21/c but the a and b axes values are the wrong way round.

**Comment by graeme-winter** [comment]
In discussion - 

 - passing unit cell and space group worked
 - there is a bug (!) in shelx perhaps that the ESD's should be propogated
 - the ideal could perhaps be passing in a reference CIF file and saying please process the data to look like this

Comments welcome
