### ISSUE TITLE
space in xinfo PROJECT name causes error

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#198]
e.g.:
`BEGIN PROJECT 9a P212121
`
etc leads to error in pointless. Possibly the filename needs quoting on input to pointless, but might be better to assert that project name contains no spaces (or strip them).

**Comment by graeme-winter** [comment]
Not allowing spaces from outset way forward. Good spot!

**Comment by graeme-winter** [comment]
Should probably do same for crystal; wavelength etc. when we do some housekeeping in this area...

**Comment by graeme-winter** [comment]
Re: releases this is not urgent & could wait for 1.9 easily - has taken 11 years for people to start putting spaces in project names...
