### ISSUE TITLE
Include some anisotropy analysis in output

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#2]
i.e. warn the general user that the data is anisotropic (or no) perhaps by including the resolution eigenvalues from ctruncate in the output? This was a request from someone at the study weekend.

**Comment by graeme-winter** [comment]
Following from xtriage (which presumably is in mmtbx => limited to chiral spacegroups) looks like what is needed:

```
       ----------Maximum likelihood anisotropic Wilson scaling----------

ML estimate of overall B_cart value:
  11.50,  0.00,  0.00
         11.50, -0.00
                 8.85

Equivalent representation as U_cif:
   0.15, -0.00, -0.00
          0.15,  0.00
                 0.11

Eigen analyses of B-cart:
  -------------------------------------------------
  | Eigenvector | Value   | Vector                |
  -------------------------------------------------
  | 1           |  11.496 | ( 0.71,  0.71, 0.00)  |
  | 2           |  11.496 | (-0.71,  0.71, -0.00) |
  | 3           |  8.847  | (-0.00,  0.00,  1.00) |
  -------------------------------------------------

```

**Comment by graeme-winter** [comment]
OK, I think I have made some headway on this however the implementation of Wilson scaling in mmtbx is I think limited to rather a low resolution => will not do what we want here (depends on static tabulated values) 

This code runs even with a centric data set but gives nonsense output; N.B. Nres here assumes 50% solvent => likely wrong if small molecule; should be > 2 x as much

Anyhow code is this:

```
from __future__ import division
from mmtbx.scaling import data_statistics
from iotbx import mtz

m = mtz.object('AUTOMATIC_DEFAULT_scaled.mtz')
mas = m.as_miller_arrays()

data = None

for ma in mas:
  if ma.is_xray_intensity_array():
    data = ma
    break

def nres_from_mtz(m):
  sg = m.space_group()
  uc = m.crystals()[0].unit_cell()
  n_ops = len(sg.all_ops())
  v_asu = uc.volume() / n_ops
  return v_asu / (2.7 * 128)

n_res = nres_from_mtz(m)
 
wilson_scaling = data_statistics.wilson_scaling(miller_array=data,
                                                n_residues=n_res)
wilson_scaling.show()
```

This produces a lot of output including but not limited to the stuff wanted above

**Comment by rjgildea** [comment]
I think the xtriage analysis in the updated xia2.html output should warn the user if anisotropy is detected.
