### ISSUE TITLE
xia2 -failover not respected with -dials pipeline

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#21]
Should be? i.e. "if something goes wrong ignore that sweep don't crash" doesn't happen:

<pre>
xia2 read_all_image_headers=false -failover -atom X /dls/mx-scratch/gw56/sbgrid/5
</pre>
...
<pre>

------------------- Autoindexing SWEEP6 --------------------
Status: error "Indexing has failed: see /dls/mx-scratch/gw56/sbgrid/xia2-dials/5-rerun/DEFAULT/SAD/SWEEP6/index/112_dials.index.log for more details."
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
</pre>

No spot finding from SWEEP6 may be a pointer...

Spot finding was run BTW

<pre>

Histogram of per-image spot count for imageset 0:
23059 spots found on 168 images (max 793 / bin)
*
*
** ***  *    *                          *
** **** **** ****                     ***
***************** **                ******
**********************             *******
************************* *      **********
**********************************************   **   **
************************************************************
************************************************************
1                         image                          168
</pre>

but indexing failed (poss: perfectly good reasons)

**Comment by graeme-winter** [comment]
Now working on this

**Comment by graeme-winter** [comment]
OK, so specific case I just checked out this worked OK (data from #29)

**Comment by graeme-winter** [comment]
Very interesting, for small molecule && multi-sweep indexing you get a bunch of errors:

```
1                         image                          850
-------------------- Spotfinding SWEEP4 --------------------


Processing sweep SWEEP1 failed: /dls/tmp/gw56/xia2-21/2/DEFAULT/NATIVE/SWEEP1/index/11_blanks.json
------- Autoindexing SWEEP1, SWEEP2, SWEEP3 & SWEEP4 -------
Processing sweep SWEEP3 failed: 'spot_lists'
Processing sweep SWEEP2 failed: 'indexed_filename'
Processing sweep SWEEP4 failed: object of type 'NoneType' has no len()
Status: error "no Integrater implementations assigned for scaling"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```

=> worthy of investigating methinks

**Comment by graeme-winter** [comment]
Command line to reproduce @DLS

```
xia2 multi_sweep_indexing=true -failover -small_molecule /dls/i19-1/data/2016/mt11231-9/MJR1901/3Al
```

**Comment by rjgildea** [comment]
Somewhat ironically:
```
$ cat /dls/tmp/rjgildea/21/DEFAULT/NATIVE/SWEEP1/index/11_dials.detect_blanks.log 
The following parameters have been modified:

output {
  json = "/dls/tmp/rjgildea/21/DEFAULT/NATIVE/SWEEP1/index/11_blanks.json"
}
input {
  datablock = 10_SWEEP4_datablock.json
  reflections = /dls/tmp/rjgildea/21/DEFAULT/NATIVE/SWEEP1/index/10_SWEEP4_strong.pickle
}

Analysis of 0 strong reflections:
Sorry: Input contains no reflections
# command line:
# dials.detect_blanks  '10_SWEEP4_datablock.json' '10_SWEEP4_strong.pickle' 'json=11_blanks.json'

```

**Comment by Anthchirp** [comment]
dials.detect_blanks failure is #29 and dials/dials#170

**Comment by graeme-winter** [comment]
Top ticket problem appears to have been resolved i.e. in an example where I am working now 

```

-------------------- Spotfinding SWEEP2 --------------------
399 spots found on 30 images (max 20 / bin)
      *    *    *           *
 *    *    *    * *       * *
 *  * *   **    ***       * *
 **** *  *** *  ****   ** * *
******* **** ** **** * ******
******* **** ****************
*****************************
******************************
******************************
******************************
1           image           30
------------------- Autoindexing SWEEP2 --------------------
Processing sweep SWEEP2 failed: Indexing has failed: see /dls/tmp/gw56/mxsw-23/DEFAULT/NATIVE/SWEEP2/index/15_dials.index.log for more details.
-------------------- Spotfinding SWEEP4 --------------------

```

**Comment by graeme-winter** [comment]
=> closing
