### ISSUE TITLE
drive (small_molecule) shelxt from command line

### ISSUE THREAD

**Issue by lksaunders** [xia2/xia2#213]
Hello,
When driving data processing manually, what is the command to also drive shelxt?
for example, something like: 
 xia2 small_molecule=true read_all_image_headers=false structure_solution=shelxt

thanks, 
Lucy

**Comment by Anthchirp** [comment]
Hi Lucy,

xia2 does not by default run shelxt, but it does produce a shelxt input file in the ```DataFiles``` directory.

What the automated processing does is:
* create a new directory names ```structure```
* copy the all files named ```shelx*``` from ```DataFiles``` into ```structure```
* then run shelxt inside the ```structure``` directory using the command
   ```shelxt shelxt```
