### ISSUE TITLE
xia2 -small_molecule max_cell=30 /dls/i19-1/data/2016/mt11238-5/2015NCS0543_dls2/

### ISSUE THREAD

**Issue by Jeppe-Christensen** [xia2/xia2#22]
trying to reprocess some old data from January 2016, and not getting the same results.
old result is in /dls/i19-1/data/2016/mt11238-5/processing/2015NCS0543_dls2/
new result is in /dls/i19-1/data/2016/mt11238-5/processing/2015NCS0543_dls2_reprocessed/
please don't overwrite any of these.

/Jeppe

**Comment by Anthchirp** [comment]
DIALS indexing error. 
New result folder is /dls/i19-1/data/2016/mt11238-5/processing/2015ncs0543_dls2_reprocessed

**Comment by Anthchirp** [comment]
This is now fixed in both DIALS 1.2.4 (_module load dials_) and the version used by _module load i19_
