### ISSUE TITLE
"Retire" mosflm / 2d pipeline

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#222]
Since I do not think this is much used and we want to move forward, need to retire to reduce amount of code to maintain. Asked CCP4; response was "if they want mosflm, use imosflm"

Obviously old versions of xia2 will be available too...

**Comment by Anthchirp** [comment]
I have marked the broken tests as expected failures for now. I think we should remove it if another test fails or we get no complaints about the deprecation?

**Comment by graeme-winter** [comment]
Agreed

**Comment by graeme-winter** [comment]
If no complaints for deprecation warning in 1.10 series => kill for 1.11

**Comment by Anthchirp** [comment]
With 2.0 out, the time for this has come.
