### ISSUE TITLE
Put more things in AutoProcProgramAttachment

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#223]
We currently only put the output log file and an mtz into this table.

You could also add:
unscaled_mtz
aimless log
various other logs that users try to get to from the current html log page.

Stu Fisher:
> I dont think we want to expose all of them. What do users want to see when they are evaulating their data?
> 
> aimless log
> pipeline log (xia2, fast_dp)
> scaled mtz
> unscaled mtz
> ... ?
> ESRF attach this lot:
> 
> di_w1_run1_noanom_xia2.html
> di_w1_run1_noanom_xia2-summary.log
> di_w1_run1_noanom_AUTOMATIC_DEFAULT_NATIVE_SWEEP1_INTEGRATE.mtz
> di_w1_run1_noanom_AUTOMATIC_DEFAULT_scaled_unmerged.mtz
> di_w1_run1_noanom_AUTOMATIC_DEFAULT_aimless.log
> di_w1_run1_noanom_AUTOMATIC_DEFAULT_pointless.log
> di_w1_run1_noanom_xia2.log
> di_w1_run1_noanom_AUTOMATIC_DEFAULT_NATIVE_SWEEP1_REFINE.log
> di_w1_run1_noanom_AUTOMATIC_DEFAULT_NATIVE_SWEEP1_LATTICE.log
> di_w1_run1_noanom_AUTOMATIC_DEFAULT_NATIVE_SWEEP1_INTEGRATE.log
> di_w1_run1_noanom_AUTOMATIC_DEFAULT_free.mtz
> di_w1_run1_noanom_AUTOMATIC_DEFAULT_NATIVE_SWEEP1_INDEX.log
> di_w1_run1_noanom_AUTOMATIC_DEFAULT_NATIVE_truncate.log

https://jira.diamond.ac.uk/browse/MXSW-953

**Comment by Anthchirp** [comment]
resolved via zocalo
