### ISSUE TITLE
Error analysis: add to xia2 report

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#234]

**Comment by benjaminhwilliams** [comment]
This still needs sorting in a way that doesn't lead to bloated DIALS and xia2 HTML reports.  It had slipped off my to-do list, so I'm re-opening this issue to prevent me neglecting it again.

**Comment by graeme-winter** [comment]
Bump

**Comment by benjaminhwilliams** [comment]
Something like this ended up in the scaling report, I believe (@jbeilstenedmands, am I right?).   @graeme-winter,  do we want it back in the xia2 report too?

**Comment by jbeilstenedmands** [comment]
Yes, a few have been included in the scaling report but not the full set that you had before. The trick to get around the memory issues is to use a numpy 2d histogram - see https://github.com/dials/dials/blob/4da6cb74965653031a86cb39a291c5f3282c2467/report/plots.py#L93 for example

**Comment by benjaminhwilliams** [comment]
Yes, I think that's what I intended to do, just never got round to it!

-- 
This e-mail and any attachments may contain confidential, copyright and or privileged material, and are for the use of the intended addressee only. If you are not the intended addressee or an authorised recipient of the addressee please notify us of receipt by returning the e-mail and do not use, copy, retain, distribute or disclose the information in or attached to the e-mail.
Any opinions expressed within this e-mail are those of the individual and not necessarily of Diamond Light Source Ltd. 
Diamond Light Source Ltd. cannot guarantee that this e-mail or any attachments are free from viruses and we cannot accept liability for any damage which you may sustain as a result of software viruses which may be transmitted in or with the message.
Diamond Light Source Limited (company no. 4375679). Registered in England and Wales with its registered office at Diamond House, Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11 0DE, United Kingdom
