### ISSUE TITLE
xia2 image= wildcard options not expanded by shell

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#237]
so if you do 

```
xia2 image=/some/unique/path/prefix*0001.cbf
```

it complains (reasonably) that the file does not exist as the shell does not know to expand things after =

**Comment by Anthchirp** [comment]
can feed through glob.glob()

Does raise the question however what the semantics of ```image=prefix*0001.cbf:20:50``` should be

**Comment by graeme-winter** [comment]
Discussion topic: would this be useful?

**Comment by graeme-winter** [comment]
Had a quick go; more complex than a 10 minute job (because file handling spread to four winds)

**Comment by benjaminhwilliams** [comment]
Yes, I think it would be useful, especially for multi-sweep data sets.  It would save a lot of typing when processing I19 data for example.  I too had a loook a little while back, but couldn't make a quick fix, so dropped it again.

Do we want to make rationalised file handling an item for the xia3 to-do list?  Side benefit: it would likely make the use of a putative functional interface to DIALS easier.

**Comment by rjgildea** [comment]
Making this work properly might be tricky. How would you distinguish/handle e.g.:
`image=prefix_*_0001.cbf` from `image=prefix_*.cbf`, `image=prefix_*_*.cbf`, `image=prefix_*.cbf:1:20` etc?
