### ISSUE TITLE
xia2 did not reprocess data after changing point group

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#251]
```cat /dls/i19-1/data/2018/sp19699-11/processed/03_sugar_150K/sugar_02_/f73f6dd3-0929-451d-b288-16d4e405ce07/xia2-dials-full/xia2.txt```

**Comment by jbeilstenedmands** [comment]
Hi Markus, can you expand on what the exact issue is. I see that multi-indexing determines P4/mmm but the data is scaled in P mmm. Is this the issue? Or did you try to run xia2 again on this, setting the point group, and then it didn't do anything?
