### ISSUE TITLE
mC / mI ambiguity in dials-full pipeline

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#260]
While mI is a mathematically recognised Bravais lattice, it is not common in MX and so xia2 has never "understood" this - with the CCP4 scaling pipeline in xia2 setting symmetry-based is used in POINTLESS to give C2 rather than I2; dials.symmetry however gives I2. 

Test case: ```/dls/mx-scratch/dials/debug-dials-full/LCY_15_15_2_0???.cbf.gz``` - 600 images, around 100MB so compact example. 

Recording here so not lost.

**Comment by rjgildea** [comment]
The scaler needs to do a similar change of basis op to reference after running dials.symmetry as we do after running dials.refine_bravais_settings, which should transform I2 to C2:
https://github.com/xia2/xia2/blob/05a26f2566c704d67de7582abe8e64d1e5e93039/Modules/Indexer/DialsIndexer.py#L536
