### ISSUE TITLE
dials-full doesn't reset properly if refiner lattice eliminated

### ISSUE THREAD

**Issue by jbeilstenedmands** [xia2/xia2#262]
After symmetry analysis in dials-full pipeline, if a lattice is eliminated, the refiner is not correctly reset to trigger reanalysis/reintegration. Needs some extra calls in DialsScaler.DialsScalerHelper - I can't remember the reason for removing this logic when constructing the pipeline, so there may be some subtle side effects to watch out for. As the triggering of this situation is somewhat of an edge case, it would be helpful to have a test/synthetic dataset. Logging here for the record.

**Comment by graeme-winter** [comment]
Assigning it to myself for coming up with that test case

**Comment by jbeilstenedmands** [comment]
The dials-full (dials) pipeline does now know how to handle lattice elimination. As there are other tickets regarding collation of test datasets, I'm closing this issue-specific ticket.
