### ISSUE TITLE
Replace xia2 Chatter/Debug streams with proper Python logging calls

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#267]

**Comment by Anthchirp** [comment]
* [ ] The next step would be to use setup_logging() in all xia2 dispatchers, at which point we can remove the reconfigure_streams_to_logging() function and roll its changes into the Chatter/Debug/Stdout classes.
* [ ] From there on we can use logging as normal throughout xia2 and have it co-exist with the stream classes for a while.
* [ ] Finally we can deprecate and remove the stream classes.
