### ISSUE TITLE
.pickle/.json to DataFiles

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#269]
When xia2 runs to completion we copy (with dials pipelines) the .json and .pickle file to the DataFiles directory.

Those files would be even more interesting in case xia2 did not run to completion.
But in those cases we don't copy the files out.
Having the most appropriate set (strong spots, indexed, integrated, ..) in a result directory would be useful.

**Comment by graeme-winter** [comment]
👍excellent idea; is new behaviour but - I think - desirable. 

Making this work gracefully will be much fun
