### ISSUE TITLE
"No associated data files found"

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#272]
Command:
```
$ xia2 trust_beam_centre=True pipeline=3dii hdf5_plugin=durin-plugin.so min_images=3 project=AUTOMATIC crystal=DEFAULT read_all_image_headers=False atom=S image=/dls/i04/data/2019/cm23004-1/tmp/Eiger/queue/Thaum/Thau_10/Thau_10_1_master.h5:1:3600
```

DIALS 1.12.3: (working directory: ```/dls/tmp/wra62962/directories/clWeqlUE```)
```
-------------------- Spotfinding SWEEP1 --------------------
Error: No associated data files found for /dls/i04/data/2019/cm23004-1/tmp/Eiger/queue/Thaum/Thau_10/Thau_10_1_master.h5
```

master: (wd: ```/dls/tmp/wra62962/directories/BUMFlvim```)
```
158402 spots found on 3600 images (max 2882 / bin)
(...)
```

Temporary copy of data made into ```/dls/tmp/wra62962/directories/X5iGNQC9``` as they were collected into visit tmp

**Comment by graeme-winter** [comment]
https://github.com/cctbx/cctbx_project/commit/a875d6bd54b1cf8c4d28fe0bf96f7815265fa798

**Comment by Anthchirp** [comment]
that one was cherry-picked to 1.12.3

**Comment by graeme-winter** [comment]
https://github.com/xia2/xia2/commit/5f1fbdea57c8c06aa026070c4d9981b0d768b3fe

**Comment by Anthchirp** [comment]
is a confirmed fix. Will go into 1.12.4 and hotfixed at DLS installation.
