### ISSUE TITLE
Mosaic retrieval fails for DialsIntegrater

### ISSUE THREAD

**Issue by humbertaco** [xia2/xia2#281]
This happens at least with the latest releases of DialsIntegrater. When the integration takes place, one of the last operations performed in the `_integrate` function is to retrieve the mosaic from the experiments list. I noticed this was failing and raising the following error:

> 'NoneType' object has no attribute 'sigma_m' @ [DialsIntegrater:383](https://github.com/xia2/xia2/blob/e0a1784de5d79cfd66979aade0b2c16b639ec97b/Modules/Integrater/DialsIntegrater.py#L383)

After some debugging, I found out a possible cause. According to the debug file that xia2 generates, I noticed the call to the method was like:

> dials.integrate  '**input.experiments=Documents/Runs/TEST/CCP4_JOBS/job_9/DEFAULT/NATIVE/SWEEP1/refine/11_refined_experiments.json**' 'nproc=12' 'input.reflections=Documents/Runs/TEST/CCP4_JOBS/job_9/DEFAULT/NATIVE/SWEEP1/refine/11_refined.pickle' 'output.experiments=13_integrated_experiments.json' 'output.reflections=13_integrated.pickle' 'output.report=13_integration_report.json' 'output.include_bad_reference=True' 'debug.reference.output=True' 'profile.fitting=True' 'outlier.algorithm=null' 'background.algorithm=glm' 'prediction.d_max=47.761689' 'prediction.d_min=0.941301'

The given input experiments corresponds to the file generated in the previous **refinement** step. This file (_11_refined_experiments.json_) is the one that the `_integrate` method tries to read in order to get the mosaic (aka _sigma_m_). However, that file does not contain any declared profile (at the very end of the file it can be read `"profile": []`, resulting in an error when trying to read the mosaic since there are no profiles to be retrieved from the file. My guess is that the program should read this parameter from another place. I assume this because the integrater generates an experiments json file which indeed includes the profile with the _sigma_m_ field available. Therefore, I assume that there is something going on in the implementation of DialsIntegrater that is messing up with the value of `self._intgr_experiments_filename = refiner.get_refiner_payload(
"experiments.json")` ([line 233 DialsIntegrater](https://github.com/xia2/xia2/blob/e0a1784de5d79cfd66979aade0b2c16b639ec97b/Modules/Integrater/DialsIntegrater.py#L233)). At this point, the integrater will have a reference to the experiments file generated by the refiner, and will be used later on to try to retrieve the profile and sigma_m, resulting in the aforementioned error.

**Comment by benjaminhwilliams** [comment]
Hi @humbertaco, thank you for the in-depth bug report and apologies that it has taken us so long to look into it.

  Is this still a problem for you with an up-to-date xia2 (or CCP4) release?  I'm struggling to reproduce what you see.  If you are still having this problem it may be that your data give rise to a corner-case problem that our test data don't account for.  If this is the case and if you're happy for us to take a look at your data to debug this further, could you perhaps send an email to xia2.support@gmail.com?

**Comment by graeme-winter** [comment]
I think this was a problem with the CCP4 distribution for a while which has since been resolved…

**Comment by benjaminhwilliams** [comment]
Oh good, I thought it was odd that we hadn't acted on this sooner.

@humbertaco, if this is still a problem for you on a more recent release, please feel free to reopen this issue.
