### ISSUE TITLE
xia2 typeerror for resolution limit chatter

### ISSUE THREAD

**Issue by jbeilstenedmands** [xia2/xia2#282]
For some rather bad datasets, if resolution determination fails this line can be called with 'None'. Same code is in CCP4ScalerA.

https://github.com/xia2/xia2/blob/e0a1784de5d79cfd66979aade0b2c16b639ec97b/Modules/Scaler/DialsScaler.py#L798

line 799, in _scale
    (sname, limit))
TypeError: float argument required, not NoneType

**Comment by graeme-winter** [comment]
+= `if is None`?

**Comment by graeme-winter** [comment]
(we probably have these issues all over the shop)

**Comment by jbeilstenedmands** [comment]
Yes should be a simple fix, although inevitably these cases are so bad that they'll probably cause a crash somewhere further down the line, so might yield multiple fixes.
