### ISSUE TITLE
xia2.report slow for large datasets

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#293]
Reportedly took 8m20s to complete on this large dataset:
```
$ pwd
/dls/mx-scratch/rjgildea/xia2-report
$ xia2.report log_include=fast_dp.log prefix=fast_dp title=fast_dp fast_dp_unmerged.mtz
```

**Comment by rjgildea** [comment]
Just reading and mtz and extracting miller arrays takes nearly 110 seconds:
```
def read_mtz(unmerged_mtz):
    from iotbx.reflection_file_reader import any_reflection_file
    reader = any_reflection_file(unmerged_mtz)
    assert reader.file_type() == "ccp4_mtz"
    arrays = reader.as_miller_arrays(merge_equivalents=False)
    return arrays
```

- 97% of the runtime is spent in iotbx.mtz.object.as_miller_arrays()
- 97% of the runtime is spent in iotbx.mtz.object.group_columns()
- 72% of the runtime is spent in cctbx.miller.array.match_bijvoet_mates (https://github.com/cctbx/cctbx_project/blob/7c7b26d5d860a2f26c8069760375b246943f3757/cctbx/miller/__init__.py#L1031)
  - via column_group()/auto_anomalous()/n_bijvoet_pairs()

**Comment by rjgildea** [comment]
group_columns(): https://github.com/cctbx/cctbx_project/blob/7cbc03abf070a35d3bb06c119fa32ec652bb95d2/iotbx/mtz/__init__.py#L611
column_group(): https://github.com/cctbx/cctbx_project/blob/7cbc03abf070a35d3bb06c119fa32ec652bb95d2/iotbx/mtz/__init__.py#L767
auto_anomalous(): https://github.com/cctbx/cctbx_project/blob/7c7b26d5d860a2f26c8069760375b246943f3757/cctbx/miller/__init__.py#L766
  - this function is called once for *every* column of data in the mtz file
n_bijvoet_pairs(): https://github.com/cctbx/cctbx_project/blob/7c7b26d5d860a2f26c8069760375b246943f3757/cctbx/miller/__init__.py#L740

**Comment by graeme-winter** [comment]
@rjgildea working on but depends on upstream changes
