### ISSUE TITLE
xia2.to_shelx crashes due to origin choice

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#3]
```
$ xia2.to_shelx  /dls/i19-1/data/2016/mt9981-21/processing/090dnw16/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz 090dnw16 FeSeLiOH

AssertionError: If the structure is centrosymmetric, the origin MUST lie on a center of
symmetry.
```

Datasets from these crystals apparently consistently need to be in 'origin choice 2'

**Comment by graeme-winter** [comment]
What do the last 3 words mean?

**Comment by Anthchirp** [comment]
Clarification by user: Space group P 4/n m m has 4 possible choices of origin, by 'choice 2' they mean literally the second option from the top in the international tables, ie. b) on http://img.chem.ucl.ac.uk/sgp/large/129a.htm

**Comment by graeme-winter** [comment]
OK, interesting - guess these are codified somewhere in smtbx?

**Comment by graeme-winter** [comment]
From shelxl manual:

'''
SYMM symmetry operation

Symmetry operators, i.e. coordinates of the general positions as given in International Tables. The operator x, y, z is always assumed, so may not be input. If the structure is centrosymmetric, the origin must lie on a center of symmetry. Lattice centering and the presence of an inversion center should be indicated by LATT, not SYMM. The symmetry operators may be specified using decimal or fractional numbers, e.g. 0.5-x, 0.5+y, -z or Y-X, -X, Z+1/6; the three components are separated by commas.
'''

**Comment by graeme-winter** [comment]
GW working on this now.

**Comment by graeme-winter** [comment]
[gw56@ws133 tmp]$ xia2.to_shelx  /dls/i19-1/data/2016/mt9981-21/processing/090dnw16/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz 090dnw16 FeSeLiOH
Atoms: FeSeLiOH
Change of basis to reference setting: a-1/4,b+1/4,c

**Comment by graeme-winter** [comment]
@rjgildea @Anthchirp please could you test the validity of the fix? seems to "work" however I am not sure if I need to verify that the cb_op.r() == I3.

**Comment by graeme-winter** [comment]
Put in assert to this effect.
