### ISSUE TITLE
current resolution cutoff rules may be inappropriate for -small_molecule data

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#30]
@Jeppe-Christensen suggested other heuristic may be required

**Comment by Jeppe-Christensen** [comment]
From the small molecule world we are used to the HKL file containing all reflections that have met the diffraction condition during the experiment and at the same time hit the detector. We do not use any filters on this file even if I/sigma <2 (which is the parameter we normally use). The filtering is done in the refinement software. On the other hand we are not so used to decaying data so we need to work out how to deal with merging such data.

**Comment by Anthchirp** [comment]
corresponding [JIRA ticket: I19-39](http://jira.diamond.ac.uk/browse/I19-39)

**Comment by graeme-winter** [comment]
If doing this then should probably report the data merging statistics overall, to 1.2 A (say) for low resolution and to 0.8A for publication, to give a reasonable idea of the completeness etc.

**Comment by graeme-winter** [comment]
#40 is part of this; perhaps all of this

**Comment by Anthchirp** [comment]
implement keep_all_reflections=true to not cut the data

small_molecule implies k_a_r=true
