### ISSUE TITLE
#329 (avoid MTZ exports) broke some tests

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#330]
Specifically
```bash
pytest --regression-full -n 3 \
  "Test/Modules/Scaler/test_CCP4ScalerA.py::test_ccp4_scalerA[1]" \
  Test/Modules/Integrater/test_DialsIntegrater.py::test_dials_integrater_serial \
  Test/Schema/test_XProject.py::test_serialization
```
as eg. the expectation is that `integrater.get_integrater_intensities()` returns an MTZ file in
https://github.com/xia2/xia2/blob/e44c603c05c92fbacaa46e44554efe82c3c5f6c0/Test/Modules/Integrater/test_DialsIntegrater.py#L56-L61
and same for `.get_reflections()` here:
https://github.com/xia2/xia2/blob/e44c603c05c92fbacaa46e44554efe82c3c5f6c0/Modules/Scaler/CCP4ScalerA.py#L194-L195

**Comment by graeme-winter** [comment]
We probably need to be explicit about this e.g. get_integrater_intensities(format="MTZ") or something and have the code transcribe the data if necessary.

In related news, should we extend `from iotbx.reflection_file_reader import any_reflection_file` to cope with DIALS reflection file formats? I can see this being problematic in terms of circular dependencies however if we had a way of using entry points or something we could extend it at run time so not have any real dependencies added...

**Comment by jbeilstenedmands** [comment]
Thanks @Anthchirp for separating this out from the other failings. My change was only intended to affect the dials/dials-full pipeline and maintain mtz export as the default for everything else, so I'll look into this now.

**Comment by jbeilstenedmands** [comment]
I've fixed the tests for now. I agree the behaviour should be more explicit, so will continue to consider the best approach here.
