### ISSUE TITLE
dials.find_spots should use a chunksize commensurate with #cores and #images

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#34]
i.e. probably not 20 in most cases - for 1800 frames a more carefully tuned #cores can save 10-15s for HDF5 data (i.e. 90 not 20 for 20 threads)

**Comment by graeme-winter** [comment]
Running same test for cbf data, will provide proper evidence for this in a moment

**Comment by rjgildea** [comment]
Shouldn't the chunksize be decided by dials.find_spots?

**Comment by graeme-winter** [comment]
perhaps, but xia2 should also be in a good position to make choices like
this (also if #machines > 1)

**Comment by graeme-winter** [comment]
mmm looks like could be more of a thing for HDF5 / Eiger than CBF files...

**Comment by rjgildea** [comment]
IMO, dials.find_spots can and should do the right thing here (>1 cores and/or >1 machine, so it makes sense for that logic to be in only one place, i.e. dials.find_spots rather than xia2.

**Comment by graeme-winter** [comment]
Agreed; see https://github.com/dials/dials/issues/150
