### ISSUE TITLE
retire xdssum?

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#351]
Anyone using this?

**Comment by graeme-winter** [comment]
What is xdssum?

p(no) >> 0

**Comment by Anthchirp** [comment]
https://github.com/xia2/xia2/blob/28769a1a48ffcd171bbba2544b4ce1b8bf378457/Modules/Indexer/IndexerFactory.py#L152

https://github.com/xia2/xia2/blob/28769a1a48ffcd171bbba2544b4ce1b8bf378457/Handlers/PipelineSelection.py#L23

**Comment by Anthchirp** [comment]
Reverend Bayes says P(no) is likely to be rather high as flake8 mentioned the following about the `__init__` function:
```
./Modules/Indexer/XDSIndexerSum.py:37:37: F821 undefined name '_index_select_images'
```

**Comment by graeme-winter** [comment]
Both barrels time then, methinks
