### ISSUE TITLE
enable multi_sweep_indexing by default for dials pipeline

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#37]
Any reason why not?

**Comment by graeme-winter** [comment]
None, though need good fallback since this depends on good gonio model (not guaranteed)

Clearly msi=false still option

**Comment by rjgildea** [comment]
No guarantee that each dataset is from the same crystal, e.g. most multi-xia2 jobs run at diamond are probably different crystals. I vote to leave default as false, i.e. only switch in if you know for sure that the datasets are from the same crystal.
