### ISSUE TITLE
Should we attempt to find the beam centre at the start?

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#373]
We currently have some code in xia2 to do this, but it has been broken since at least DIALS 1.1, so I will remove that shortly.

It is obviously not strictly needed. Should we reintroduce this?

**Comment by Anthchirp** [comment]
Update: We _do_ run a per-sweep beam centre search in the DIALS indexer. See ac489ab063faa10453d7551d46e453af6e424c3c

**Comment by graeme-winter** [comment]
iff `trust_beam_centre is False`
