### ISSUE TITLE
Integrated .expt/.refl not saved to DataFiles if indexing solutions eliminated

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#379]
If xia2 goes through cycles of eliminating indexing solutions, eventually choosing the P1 solution, and then re-indexes/integrates the data, then it seems that the integrated expt/refl files are never saved to the DataFiles directory:
```
$ xia2 image=/dls/mx/data/mx17352/mx17352-126/VMXi-AB0440/well_45/images/image_7985.nxs remove_blanks=True
...
-------------------- Preparing DEFAULT ---------------------
Eliminating indexing solution:
tP  58.59  58.59 151.07  90.00  90.00  90.00
Eliminating indexing solution:
oC  82.85  82.86 151.06  90.00  90.00  90.00
Eliminating indexing solution:
oP  58.75  58.59 151.03  90.00  90.00  90.00
Eliminating indexing solution:
mC  83.19  83.03 151.82  90.00  89.81  90.00
Eliminating indexing solution:
mP  58.62  58.71 151.20  90.00  89.90  90.00
-------------------- Preparing DEFAULT ---------------------
------------------- Autoindexing SWEEP1 --------------------
All possible indexing solutions:
aP  58.83  58.79 151.81  89.78  89.89  89.81
Indexing solution:
aP  58.84  58.80 151.82  90.24  90.11  89.79
-------------------- Integrating SWEEP1 --------------------
...
```
Content of `DataFiles` directory (`AUTOMATIC_DEFAULT_NATIVE_SWEEP1.{expt,refl}` are missing):
```
$ ls DataFiles/
AUTOMATIC_DEFAULT_free.mtz  AUTOMATIC_DEFAULT_scaled.expt  AUTOMATIC_DEFAULT_scaled.mtz  AUTOMATIC_DEFAULT_scaled.refl	AUTOMATIC_DEFAULT_scaled_unmerged.mtz  xia2.cif  xia2.mmcif
```
Expected content:
```
$ ls DataFiles/
AUTOMATIC_DEFAULT_free.mtz	      AUTOMATIC_DEFAULT_NATIVE_SWEEP1.refl  AUTOMATIC_DEFAULT_scaled.mtz   AUTOMATIC_DEFAULT_scaled_unmerged.mtz  xia2.mmcif
AUTOMATIC_DEFAULT_NATIVE_SWEEP1.expt  AUTOMATIC_DEFAULT_scaled.expt	    AUTOMATIC_DEFAULT_scaled.refl  xia2.cif
```

When the `DialsIntegrater._integrate_finish()` method is called, `self._intgr_reindex_operator` is always `None`, meaning that the method returns early and never reaches the point where `FileHandler.record_more_data_file()` is called:
https://github.com/xia2/xia2/blob/f0ef1dda6f0c6974c4e08780355152dd9aa21ea8/Modules/Integrater/DialsIntegrater.py#L482-L503

https://github.com/xia2/xia2/blob/f0ef1dda6f0c6974c4e08780355152dd9aa21ea8/Modules/Integrater/DialsIntegrater.py#L542-L549

**Comment by rjgildea** [comment]
`DialsIntegrater._intgr_reindex_operator` only seems to get set if `DialsScalerHelper.reindex_jiffy()` is called, which for some reasons seems not to be the case in the above example:
https://github.com/xia2/xia2/blob/f0ef1dda6f0c6974c4e08780355152dd9aa21ea8/Modules/Scaler/DialsScaler.py#L1181-L1194

**Comment by jbeilstenedmands** [comment]
Possibly relevant line, where the reindex_operator is lost:
https://github.com/xia2/xia2/blob/f0ef1dda6f0c6974c4e08780355152dd9aa21ea8/Schema/Interfaces/Integrater.py#L280-L287
