### ISSUE TITLE
Please can we make the output go somewhere other than $CWD

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#38]
Some people want this very much, I am not totally sure the reason but they are clear so...

**Comment by graeme-winter** [comment]
Turns out this is dependent on #42

**Comment by graeme-winter** [comment]
Why? Because the change of working directory needs to be the very first thing we do, so this needs to be parsed from the Phil file before any other commands are executed e.g. setting up the environment.

**Comment by Anthchirp** [comment]
requested by user
