### ISSUE TITLE
Is this redundant code?

### ISSUE THREAD

**Issue by benjaminhwilliams** [xia2/xia2#403]
A fair amount of water has gone under the bridge while this 'temporary workaround' watches on.  Is it still necessary?  An opportunity for a tidy-up?

https://github.com/xia2/xia2/blob/4a549d8b5b7c711b1173ffee319d409fe1bf686e/Modules/Refiner/DialsRefiner.py#L114-L115

It was introduced as https://github.com/xia2/xia2/commit/b009757.

**Comment by rjgildea** [comment]
Probably one to ask @dagewa if it is still relevant.

**Comment by dagewa** [comment]
I have no idea. It's not clear what the dials.refine error was, but the workaround (not doing scan-varying refinement for narrow wedges) does seem sensible.

**Comment by benjaminhwilliams** [comment]
Closed by cb1b853b.
