### ISSUE TITLE
XIA2Version.py is capitalized in HEAD but not in setup.py

### ISSUE THREAD

**Issue by tjlane** [xia2/xia2#440]
And this breaks `python setup.py install`

https://github.com/xia2/xia2/blob/6c64be5fba4d366ad439d96efeca4ea33f0ec8d6/setup.py#L38

**Comment by Anthchirp** [comment]
While this is technically true, a word of caution: xia2 depends on https://github.com/dials/dials which in turn depends on cctbx, which requires a very specific python environment. As a result you won't be able to treat xia2 as a normal python package that you can just `pip install` / `python setup.py install`. So while this may now give you a successful return value it will most likely not give you what you expect.

To get a working xia2 environment I suggest downloading a release from https://github.com/dials/dials/releases (xia2 is included with DIALS), with further information at https://dials.github.io/installation.html

**Comment by tjlane** [comment]
Yep I am aware ;). Thanks!!!
