### ISSUE TITLE
Is Python3 supported ?

### ISSUE THREAD

**Issue by picca** [xia2/xia2#450]
While preparing a package od dials for Debian, I got this error mesage, when trying to run
xia2

```
:~/Téléchargements/build_master/debian/output$ xia2 --help
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages//xia2/command_line/xia2_main.py", line 29, in <module>
    from xia2.Schema.XProject import XProject
  File "/usr/lib/python3/dist-packages/xia2/Schema/XProject.py", line 11, in <module>
    import pathlib2
ModuleNotFoundError: No module named 'pathlib2'
```

so my question is does xi2 support Python3

**Comment by Anthchirp** [comment]
Yes, from DIALS 2.2 onwards xia2 supports Python 3. The equivalent xia2 version is 0.6.446.

However xia2 for now still supports Python 2, as described in the timeline in dials/dials#1175, so relies on `pathlib2` to provide a compatibility layer.
