### ISSUE TITLE
i2 xia2 interface needs to be clearer

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#5]
i.e. (i) be clear that directories are being passed or (ii) allow the option of passing specific images etc. This is one to discuss with @dagewa

**Comment by DiamondLightSource-build-server** [comment]
No progress has been noted on this issue for a year. You may want to take another look at it some time. I will mark it as 'stale'. Please remove the marker if this is still being worked on.

**Comment by graeme-winter** [comment]
David is working on this

**Comment by graeme-winter** [comment]
@dagewa

**Comment by dagewa** [comment]
Limitations in i2... "Location of images" label now changed to "Location of directory containing images". At least this will help.
