### ISSUE TITLE
Recent changes broke xinfo functionality (possibly others)

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#50]
Sorry more random xia2 queries, things we working fine last week and now it seems xia2 is doing something funny with the file template which i dont understand, my sweep looks like this:

DIRECTORY /dls/i03/data/2016/cm14451-3/tmp/2016-06-13/fake114652/
IMAGE X1_strong_M1S1_2_0001.cbf
START_END 133 160

but im getting RuntimeError: no Integrater implementations assigned for scaling

digging a bit deeper i find

/dls/i03/data/2016/cm14451-3/.ispyb/processing/tmp/2016-06-13/fake114652/X1_strong_M1S1_2/run_5/DEFAULT/NATIVE/SWEEP1/index/2_INIT.LP

NAME_TEMPLATE_OF_DATA_FRAMES=/dls/i03/data/2016/cm14451-3/tmp/2016-06-13/fake114652/X1_strong_M1S1_2_01??.cbf
DATA_RANGE=133 160
SPOT_RANGE=133 160

clearly this NAME_TEMPLATE is wrong, it should have been ???? rather than 2 question marks. Any ideas how ive messed this up?

Working directory and related scripts are in:

/dls/i03/data/2016/cm14451-3/.ispyb/processing/tmp/2016-06-13/fake114652/X1_strong_M1S1_2/run_5

**Comment by graeme-winter** [comment]
Easier reproducer:

```
Graemes-MacBook-Pro-4:xia2-50 graeme$ xia2 pipeline=3dii image=/Users/graeme/data/i04-bag-training/th_8_2_0001.cbf:120:180
Environment configuration...
Python => /Users/graeme/svn/cctbx/build/../base/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
CCTBX => /Users/graeme/svn/cctbx/modules
CCP4 => /Applications/ccp4-7.0
CLIBD => /Applications/ccp4-7.0/lib/data
CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmpJHhQpK
Starting directory: /private/tmp/xia2-50
Working directory: /private/tmp/xia2-50
Free space:        47.36 GB
Contact: xia2.support@gmail.com
XIA2 0.4.0.509-gf531fa5
DIALS 1.dev.514-gbd0849e
Command line: xia2 pipeline=3dii image=/Users/graeme/data/i04-bag-training/th_8_2_0001.cbf:120:180
-------------------- Spotfinding SWEEP1 --------------------
Status: error "[Errno 2] No such file or directory: '/private/tmp/xia2-50/DEFAULT/NATIVE/SWEEP1/index/INIT.LP'"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```

**Comment by graeme-winter** [comment]
Perhaps unconnected this is also not respected correctly for HDF5 data files:

```
DIALS 1.dev.526-g26ce05d
Command line: xia2 image=../thaumatin28_w1_3_1_master.h5:40:80
-------------------- Spotfinding SWEEP1 --------------------
79338 spots found on 100 images (max 1870 / bin)
                                                           *
                          **             *     ** ** ** ** *
              *   * ** ** ** ** ** ** ** ** ** ** ** ** ** *
*       ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** *
* ** ** ** ** ** ** ** ** ***** ** ** ** *******************
* ** *******************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                          100
------------------- Autoindexing SWEEP1 --------------------
```

**Comment by rjgildea** [comment]
Not related to current bug but relative path HDF5 issue fixed by https://github.com/xia2/xia2/commit/417d72bbded4da0533a6e0eb27a13493134cfbc5
