### ISSUE TITLE
xia2.small_molecule pipeline=3dii gives some weird output

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#54]
In particular:

```
--------------------- Scaling DEFAULT ----------------------
Resolution for sweep NATIVE/SWEEP1: 0.00
```

suspect we have some emergent behaviour here - if this is keeping all reflections then should probably at least report a sensible limit...

**Comment by graeme-winter** [comment]
Same job using DIALS pipelines gives

```
--------------------- Scaling DEFAULT ----------------------
Resolution limit for NATIVE/SWEEP1:  0.66
```

i.e. sensible limit

**Comment by rjgildea** [comment]
Presumably these changes to CCP4ScalerA.py also need applying to XDSScalerA.py: https://github.com/xia2/xia2/commit/13c68fa5c968ef6e3a2096babb7552890d65da65#diff-5857350e6a95da6febca12b7b1ab67c0L1074
