### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by ndevenish** [xia2/xia2#557]
I propose we do this Monday 18th January.

GitHub has now rolled out their mechanism for seamlessly renaming the branch, and migrating issues and pull requests: https://github.com/github/renaming#creating-a-seamless-move-for-existing-repositories-

Therefore, we can now do this. This repository and pull requests will be automatically migrated. Any developer installs will have to be manually migrated. GitHub's instructions for the branch rename propose:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
which will apparently show as a notification to users of the repository. We could put in something more complicated but I think the collection of active developers is small enough not to warrant it?

**Comment by Anthchirp** [comment]
likely true. bootstrap will need concomitant updating.

**Comment by Anthchirp** [comment]
Discussed in https://dials.github.io/kb/core/20210114#renaming-master-branch--main, need to define a breakage message in a pull request before migrating the default branch name,

**Comment by biochem-fan** [comment]
@Anthchirp

I came across your message introduced in 2abb25e.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

were not enough in my case. I had to perform `git pull` after this.

**Comment by Anthchirp** [comment]
I assumed it was implicit that you'd need to update the sources afterwards, but can definitely see how it isn't. We'll make the instructions clearer when we make the move for dials etc.

Thanks!

👍
