### ISSUE TITLE
UnicodeEncodeError on Windows

### ISSUE THREAD

**Issue by ndevenish** [xia2/xia2#558]
Edited report from Charles:
> This is with 2.2.10 as I have not (but are about to) started 3.2.X.  Logging on windows is causing me issues as it defaults to cp1252 .......  have various characters like sigma which are not supported on cp1252.  Even using PYTHONIOENCODING I still get issues.  My "fix" is to force utf-8 for the encoding of various strings such as those in symmetry/__init__.py and xia2_main.py (line 337)...... cannot do sys.stdout like that.

```
--- Logging error ---
Traceback (most recent call last):
File "C:\msys64\je\workspace\CCP4\py3-win10-gcc\devtools\test-install\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
File "C:\msys64\je\workspace\CCP4\py3-win10-gcc\devtools\test-install\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u25ef' in position 12: character maps to <undefined>

Call stack:
    File "C:\msys64\je\workspace\CCP4\py3-win10-gcc\devtools\test-install\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
    File "C:\msys64\je\workspace\CCP4\py3-win10-gcc\devtools\test-install\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
    File "C:\msys64\je\workspace\CCP4\py3-win10-gcc\devtools\test-install\lib\py2\site-packages\xia2\command_line\xia2_main.py", line 356, in <module>
        run()
    File "C:\msys64\je\workspace\CCP4\py3-win10-gcc\devtools\test-install\lib\py2\site-packages\xia2\command_line\xia2_main.py", line 337, in run
        logger.debug("\n".join(xia2.Driver.timing.report()))
Message: "...... \u25ef ......."
Arguments: ()
```

This doesn't seem to have an easy solution.

Immediate thoughts:
- [`PYTHONIOENCODING`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING) apparently works on windows if [`PYTHONLEGACYWINDOWSSTDIO`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONLEGACYWINDOWSSTDIO) is set.
- The thread https://bugs.python.org/issue37111 seems to discuss this issue somewhat contentiously but results in a [change](https://github.com/python/cpython/commit/ca7b504a4d4c3a5fde1ee4607b9501c2bab6e743) that adds error/encoding handlers to `logging.basicConfig` - but for Python 3.9+.
- `StreamHandler` apparently doesn't have an encoding/error attribute but we could make a custom handler that does the conversion with unicode error handling/do something else where we construct it - look like: https://github.com/xia2/xia2/blob/4ad82a56e11a5a737d46618ab6c0137fa328eec7/src/xia2/Handlers/Streams.py#L63-L66

**Comment by Anthchirp** [comment]
Reproducer:

```python
import logging
import sys

snowman = "\U00002603"
print("snowman character:", snowman.encode("latin-1", errors="namereplace"))

log = logging.getLogger()
loglevel = logging.INFO
console = logging.StreamHandler(sys.stdout)
console.setLevel(loglevel)
log.setLevel(loglevel)
log.addHandler(console)

log.info("Part 1: logging to console")
log.info(snowman)

fh = logging.FileHandler(filename="demo.txt", mode="w")
fh.setLevel(loglevel)
log.addHandler(fh)

log.info("Part 2: logging to console and file")
log.info(snowman)
```

Output on Windows (Python 3.8.6):
![image](https://user-images.githubusercontent.com/2102431/104733825-2f1a4280-5737-11eb-9f22-2e6530924687.png)

indicates that logging to console is not the issue, logging to the file is.
And sure enough
```diff
-fh = logging.FileHandler(filename="demo.txt", mode="w")
+fh = logging.FileHandler(filename="demo.txt", mode="w", encoding="utf-8")
```
leads to
![image](https://user-images.githubusercontent.com/2102431/104733949-5ffa7780-5737-11eb-9d18-f838e0c475e2.png)
and
![image](https://user-images.githubusercontent.com/2102431/104733973-6b4da300-5737-11eb-8925-9586e9b69d74.png)

Suggested patch coming up.
