### ISSUE TITLE
Cannot process reversed scans

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#56]
One positive omega scan, one negative omega scan:
`$ xia2.small_molecule image=/dls/i19-2/data/2016/cm14477-3/processing/EH2_reverse_scans/nott300_4_edit/nott300_3_00001.cbf image=/dls/i19-2/data/2016/cm14477-3/processing/EH2_reverse_scans/nott300_4_edit/nott300_5_00001.cbf`

Now crashes with
`Status: error "dials.detect_blanks terminated with an error: (..)"`

Need to modify/invert the dxtbx goniometer so that the scans are in positive direction, as a number of programs use that assumption internally.

**Comment by graeme-winter** [comment]
Working on this now; BTW the beam centre is off by a fair margin...

**Comment by graeme-winter** [comment]
svn commit -m "Handle reversed scans in imgCIF; inverts axis & angles; appears to work correctly with example in xia2-#56; fixes same"
Sending        goniometer_helpers.py
Sending        scan.py
Transmitting file data ..
Committed revision 25079.

**Comment by graeme-winter** [comment]
@Anthchirp please test & close if appropriate

**Comment by graeme-winter** [comment]
Additional: while this "worked" there is something very weird with some of the indexed lattices i.e. experiment 0 indexed reflections look like...
<img width="792" alt="screen shot 2016-07-27 at 08 27 19" src="https://cloud.githubusercontent.com/assets/1241716/17167233/f7f78d00-53d3-11e6-8d05-7c4c8be48866.png">
