### ISSUE TITLE
merge xia2.to_shelx into xia2

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#62]
atom designations via elements=CNOH (default)

Open questions:
- write to shelx.ins/hkl or $CRYSTAL.ins/hkl or $PROJECT.ins/hkl?
- what about multiple wavelength case?

**Comment by graeme-winter** [comment]
See also xia2.to_shelxcde

**Comment by Anthchirp** [comment]
A question that came up describing the xia2 output files.
Should the ins/hkl files end up in the DataFiles directory?
Presumably this would make sense.

(Offtopic: What about xia2.cif/.mmcif?)

**Comment by Anthchirp** [comment]
Remaining question: which one of those three routes should we go down?
  - should _atoms=CNOH_ be default and shelxt export use _atoms_?
  - should _atoms=CNOH_ be default when _small_molecule=true_ and shelxt export use _atoms_?
  - should shelxt export use different phil parameter _elements_ which defaults to CNOH?

**Comment by graeme-winter** [comment]
OK several comments
- should set anomalous=true by default @rjgildea have you an opinion?
- set atoms=CNOH by default always
- if user sets atom=Ni (say) on cmd line then append this
- if user sets atoms=CNOHSNi take heaviest atom as atom= (though is this needed if we have anomalous=true by default?!)
- keep in mind user may set atoms=C21H30O2 or similar - cope with this

**Comment by graeme-winter** [comment]
If we set anomalous=true by default could we / should we retire atom= or just pun it to atoms=?
