### ISSUE TITLE
Handling of multiple wavelengths in xia2.multiplex

### ISSUE THREAD

**Issue by jbeilstenedmands** [xia2/xia2#632]
I accidentally ran multiplex on a dataset with multiple wavelengths, which caused a crash:
```Traceback (most recent call last):
  File "/dials/build/../conda_base/python.app/Contents/bin/xia2.multiplex", line 33, in <module>
    sys.exit(load_entry_point('xia2', 'console_scripts', 'xia2.multiplex')())
  File "/dials/modules/xia2/src/xia2/cli/multiplex.py", line 159, in run
    ScaleAndMerge.MultiCrystalScale(experiments, reflections_all, params)
  File "/dials/modules/xia2/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 497, in __init__
    convert_merged_mtz_to_sca("scaled.mtz")
  File "/dials/modules/xia2/src/xia2/Modules/Scaler/DialsScaler.py", line 1444, in convert_merged_mtz_to_sca
    raise KeyError("Intensity column labels not found in MTZ file")
KeyError: 'Intensity column labels not found in MTZ file'
```

The specific issue here is that this convert function expects a merged mtz file containing data from a single wavelength, and the "scaled.mtz" contains two wavelengths, with column labels `I_WAVE1(+)` etc. 
I think in general, we probably want the behaviour to match the regular xia2 pipeline: after scaling, the data is split by wavelength for the purpose of creating the mtz files, so that there is one merged and unmerged mtz output per wavelength. Then this function call will work as expected.

**Comment by MartinMalyMM** [comment]
Thank you for dealing with that issue.
Please could be there also an option that would scale and merge data sets with different wavelengths together?
What is the best approach with the currently available tools now? I am wondering about brute-force modification of wavelengths in the integrate.expt files (set to just 1 wavelength) that would go as the input to xia2.multiplex.
