### ISSUE TITLE
Huge xia2.json files

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#65]
A `find /dls/i19-1 | grep xia2.json | xargs ls -la | sort -k 5 -n` shows at least 110 xia2.json files with sizes above 100 MB. They all seem to relate to charged density collections, most of them marked as xia2.multi-sweep. The latter, since those two are not strictly independent, may not mean much, however.

The smallest file above 100MB is ./cm14476-1/processed/20160310_collectionTest/23_chargedensity_0-2s_0-2d/8/xia2.multi-sweep/xia2.json
Among the largest offenders backed with a realistic data collection strategy is /dls/i19-1/data/2016/s_3_-6/processing/_u_/_8_i/xia2.json from June with 451 MB.
The most outrageous file is /dls/i19-1/data/2016/mt11238-7/processed/nidppecl2_d_phiscans/22/xia2.multi-sweep/xia2.json with 3.3 GB.

**Comment by graeme-winter** [comment]
On plus side, it compresses well - your 100MB example:

huge.json: 134.970:1,  0.059 bits/byte, 99.26% saved, 103285194 in, 765246 out.

**Comment by graeme-winter** [comment]
OK in dxtbx serialise / un serialise, if epoch = [number, 0, 0, 0, 0....] could just assume 0-packed (same for exp time) & have the object return 0's @jmp1985 what do you think? would remove many many records from this file. Also json without nice spaces i.e. not human readable would free up most of the bytes. In json.dump() set indent=None for "most compact representation".

**Comment by graeme-winter** [comment]
OK, so removing the spaces & 0's would remove > 90% of the bytes, probably > 97%:

```
Graemes-MacBook-Pro-4:tmp graeme$ cat huge.json | grep '  0.0,' | awk '{print $1}' | uniq
0.0,
Graemes-MacBook-Pro-4:tmp graeme$ cat huge.json | grep '  0.0,' | awk '{print $1}' | wc -l
 2711638
Graemes-MacBook-Pro-4:tmp graeme$ wc -l huge.json 
 3085851 huge.json
```

**Comment by graeme-winter** [comment]
Removing spaces would solve 82% of the problem:

```
Graemes-MacBook-Pro-4:tmp graeme$ dials.python
Python 2.7.8 (default_cci, Mar 19 2015, 08:06:01) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> d = json.load(open('huge.json'))
>>> json.dump(d, open('smaller.json', 'w'), indent=None)
```

```
Graemes-MacBook-Pro-4:tmp graeme$ ls -l *json
-rw-r-x---  1 graeme  wheel  103285194 19 Aug 06:28 huge.json
-rw-r--r--  1 graeme  wheel   18493787 19 Aug 06:38 smaller.json
```

0 cost solution?! 0-packing would solve most of the rest...

**Comment by graeme-winter** [comment]
I note also in cctbx_project/dxtbx/serialize.py: def imageset_to_string(obj, compact=False):

If we just switched to "true" for compact what would be cost?!

**Comment by graeme-winter** [comment]
@rjgildea this was in your area back in the day...

**Comment by graeme-winter** [comment]
Thinking an option is to make this a phil param? compact_json = True or similar?

**Comment by Anthchirp** [comment]
doesn't look like there is a real need for such an option. Think this can be closed.
