### ISSUE TITLE
cluster_method=unit_cell causes an "Invalid cluster method" error

### ISSUE THREAD

**Issue by biochem-fan** [xia2/xia2#654]
`xia2.multiplex -ce3` shows `unit_cell` as a `cluster_method` as defined in https://github.com/xia2/xia2/blob/main/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py#L225.

```python
cluster_method = *cos_angle correlation unit_cell
  .type = choice
  .short_caption = "Metric on which to perform clustering"
```

However, this leads to an `Invalid cluster method` error:
https://github.com/xia2/xia2/blob/main/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py#L545
```python
        if self._params.cluster_method == "cos_angle":
            clusters = self._cos_angle_clusters
        elif self._params.cluster_method == "correlation":
            clusters = self._cc_clusters
        else:
            raise ValueError("Invalid cluster method: %s" % self._params.cluster_method)
```

**Comment by rjgildea** [comment]
This option was added as a placeholder for unimplemented additional clustering on unit cell parameters. To avoid confusion, I've removed the placeholder option until such time as we decide to implement the feature.
