### ISSUE TITLE
processing multiple run datasets - nxs files from Tristan 10M detector

### ISSUE THREAD

**Issue by drmrw** [xia2/xia2#671]
Hi, 

During the beamtime we could not process multi-run datasets using the normal routines.

visit: /dls/i19-2/data/2022/cy30210-1

datasets to process together: 
206a_PtCmpd_100K_50kHz_ND2_SS
206b_PtCmpd_100K_50kHz_ND2_SS

nxs files: 
/dls/i19-2/data/2022/cy30210-1/processing/206a_PtCmpd_100K_50kHz_ND2_SS/PtCmpd_1_images.nxs
/dls/i19-2/data/2022/cy30210-1/processing/206b_PtCmpd_100K_50kHz_ND2_SS/PtCmpd_2_images.nxs

example xia2 command: 
xia2 small_molecule=true image=/dls/i19-2/data/2022/cy30210-1/processing/206a_PtCmpd_100K_50kHz_ND2_SS/PtCmpd_1_images.nxs image=/dls/i19-2/data/2022/cy30210-1/processing/206b_PtCmpd_100K_50kHz_ND2_SS/PtCmpd_2_images.nxs

Please can you have look into why this might be?

**Comment by graeme-winter** [comment]
Wilco, thanks for the issue report. Will investigate.

**Comment by graeme-winter** [comment]
OK, looking at this now, looks like HDF5 "master files" get special treatment - which would obviously not apply here as these are NeXus files _however_ I suspect there is some cross-talking taking place here.

**Comment by graeme-winter** [comment]
PFoB => `_filter_aliased_hdf5_sweeps`
