### ISSUE TITLE
Status: error "XDS refinement failed (no mosaic spread range reported)"

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#7]
`xia2 reference_geometry /dls/i19-2/data/2015/cm12173-3/processing/150518_bruker_test/xia2_3dii/010.json -3dii -small_molecule space_group=P21/c unit_cell=11.358,13.327,15.904,90,98.896,90 multi_sweep_indexing=true /dls/i19-2/data/2015/cm12173-3/150518_bruker_test/010_Ni_dppe_Cl_2_150K -no_profile`

-------------------- Integrating SWEEP1 --------------------
Processed batches 1 to 325
Standard Deviation in pixel range: 0.440000 0.500000
Integration status per image (60/record):
(..)
Maximum relative deviation in cell: 0.002
Mosaic spread: 0.190 < 0.190 < 0.190
-------------------- Integrating SWEEP2 --------------------
Status: error "XDS refinement failed (no mosaic spread range reported)"

Likely to be caused by `multi_sweep_indexing=true` together with `-3dii`. Do we expect this to work?

**Comment by graeme-winter** [comment]
No this is not expected to work however data are no longer present on disk it seems anyway?
