### ISSUE TITLE
Multiplex: how does one use the `identifiers` option?

### ISSUE THREAD

**Issue by dagewa** [xia2/xia2#751]
I would like to select the cluster merged by the purple line (on the upper dendrogram), but I failed to set `max_clusters` high enough when I ran the job. 
![newplot (4)](https://github.com/xia2/xia2/assets/11502083/4e258fa0-c8de-47f4-9c0f-8c9694f0902b)

I saw the `identifiers` option and figured perhaps it is a way to manually define a cluster of interest (I can't be sure as it has no PHIL help string). With that in mind, I copied the relevant datasets line out of the HTML table and re-ran my job like this, but it crashed:

```
$ xia2.multiplex ../scale-larger-cell-05/combined.{expt,refl} resolution.d_min=0.52 multi_crystal_analysis.unit_cell=14.467,21.862,17.717,90,90.11,90 identifiers="0 3 4 5 7 8 9 10 11 12 13 14 15 17 18 19 23 26 28 30 31 32 33 34 35 38 39 41 42 43 44 45 46 50 51 52 55 56 57 58 60 62 63 64 65 66"
DIALS 3.dev.997-gda59c1d80
The following parameters have been modified:

resolution {
  d_min = 0.52
}
multi_crystal_analysis {
  unit_cell = 14.467 21.862 17.717 90 90.11 90
}
identifiers = "0" "3" "4" "5" "7" "8" "9" "10" "11" "12" "13" "14" "15" "17" \
              "18" "19" "23" "26" "28" "30" "31" "32" "33" "34" "35" "38" \
              "39" "41" "42" "43" "44" "45" "46" "50" "51" "52" "55" "56" \
              "57" "58" "60" "62" "63" "64" "65" "66"
input {
  experiments = ../scale-larger-cell-05/combined.expt
  reflections = ../scale-larger-cell-05/combined.refl
}

/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/site-packages/numpy/core/_methods.py:261: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/xia2/bin/xia2.multiplex", line 33, in <module>
    sys.exit(load_entry_point('xia2', 'console_scripts', 'xia2.multiplex')())
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/cli/multiplex.py", line 167, in run
    ScaleAndMerge.MultiCrystalScale(experiments, reflections_all, params)
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 357, in __init__
    self.unit_cell_clustering(plot_name="cluster_unit_cell_p1.png")
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 685, in unit_cell_clustering
    clustering = MultiCrystalAnalysis.unit_cell_clustering(
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystalAnalysis.py", line 91, in unit_cell_clustering
    clustering = cluster_unit_cells(
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/clustering/unit_cell.py", line 196, in cluster_unit_cells
    a = uc[:, 0] ** 2
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by amyjaynethompson** [comment]
Hi, I've done some testing and it seems that the "identifiers" option is referring to the unique identifier code that dials assigns, which can be found in your .expt file under 'identifier'. 

If you convert the dataset numbers to the identifiers, then you could do exactly as you described and re-run multiplex for a single cluster. I am currently working on a more user friendly way to do this, so thank you for bringing this to my attention. 

In the meantime, an option to get around converting datasets to identifiers would be to run xia2.cluster_analysis -  you can input the scaled.expt and scaled.refl files from the full multiplex run and it will essentially repeat the clustering analysis done by mulitplex, but there are additional phil options to output a specific cluster (ie output_cos_cluster=x, where x is the cluster number you want and can be found in the xia2.multiplex.html file). This will output a scaled.expt and scaled.refl containing only the datasets in that cluster, which dials.merge can then convert to the final .mtz. 

Hope this helps and let me know if I can help further :)

**Comment by dagewa** [comment]
Thanks, that sounds good! I will try the `xia2.cluster_analysis` route. You have also answered my question, so closing this :+1:

**Comment by dagewa** [comment]
Although, as an after-thought, it would be nice if the PHIL definition here had a help string:
https://github.com/xia2/xia2/blob/d86968d8cd8c1142a0da79fb0b353a7e08c39bf5/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py#L241-L243
So, I'll reopen for now...
