### ISSUE TITLE
Implement mechanism for keying mmCIF beamline definitions to dxtbx objects

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#78]
As per title really, some mechanism which will allow

```
dxtbx.get_mmcif_beamline_definition(detector_sn_or_key, timestamp)
```

will copy in beamline definitions in a moment

Something extensible in the manner of dxtbx would be good... perhaps living in dxtbx/data?

**Comment by Anthchirp** [comment]
Also want cif output

**Comment by graeme-winter** [comment]
http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v40.dic/Categories/diffrn_source.html
http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v40.dic/Items/_diffrn_source.pdbx_synchrotron_site.html

should scrape out some examples from pdb, guess little molecule people want same (easier, fewer instruments to consider)

**Comment by Anthchirp** [comment]
```bash
$ cat /dls_sw/i19-1/etc/cif/i19-1.cif
data_i191
_audit_creation_date              2016-08-25

_diffrn_detector                  'Photon counting pixel array'
_diffrn_detector_type             'Dectris Pilatus 2M'
_diffrn_measurement_device        'Fixed \c 3-circle diffractometer'
_diffrn_measurement_device_type   'Fluid Film Devices'
_diffrn_measurement_method        '\f rotation with 0.1 degree frames'
_diffrn_measurement_specimen_support    'MiTeGen MicroMount'
_diffrn_radiation_type            'Synchrotron'
_diffrn_radiation_source          'Diamond Light Source Beamline I19'
_diffrn_radiation_monochromator   'Silicon 111'

_computing_data_collection        'GDA 8.44; generic data acquisition software'
```

**Comment by graeme-winter** [comment]
Yup this would be a good start, though I don;t think we know about _diffrn_measurement_specimen_support as a rule.... && rotation axis could be different (what happens for multi-scan data? or data from > 1 beamline?)

**Comment by Anthchirp** [comment]
if >1 detector or >1 beamline we could start using lists, but really we would have a problem

**Comment by graeme-winter** [comment]
@rjgildea any clue what is the right thing to do here? @dagewa ISTR you went to the mmCIF workshop last week perhaps you have an idea?

**Comment by dagewa** [comment]
Not really, we didn't touch on this. It was more about new mmCIF
definitions to represent unmerged datasets.

**Comment by Anthchirp** [comment]
now can run ```xia2 detector_id="PILATUS 2M, S/N 24-0107 Diamond"``` which will pretend data were collected with detector on I19.
Actual detection of detector identity depends on dials/dials#219 and corresponding changes in dxtbx format classes and the dxtbx database.
Once the detector object interface is defined the call in ```Schema/XSweep.py:get_detector_identification``` can be amended and this issue closed.
