### ISSUE TITLE
radiation damage series?

### ISSUE THREAD

**Issue by mysecondnameisdanger** [xia2/xia2#781]
How do treat radiation damage series?
Let's say I collected the same dataset from the same crystal many times...(each time with 2 sweeps, defined in the `master.h5` file).

I am doing a simple for loop in `bash` like this ..

```
#!/bin/bash
# First crystal
for i in `seq -w 49 72`
do
  mkdir ${i}
  # run xia2 in the folder with the datasets
  xia2 pipeline=dials space_group=X /home/msnid/NSLS2/${i} image=/home/msnid/NSLS2/Test-msnid-3-15_122${i}_master.h5
done

```

Is this the correct way to do it?

**Comment by graeme-winter** [comment]
Picking up https://github.com/dials/dials/issues/2629
