### ISSUE TITLE
Recalculate batch offsets after cosym

### ISSUE THREAD

**Issue by biochem-fan** [xia2/xia2#787]
@graeme-winter 

Now that [dials.cosym filters out datasets that can't be mapped through a consistent best cell, rather than exiting](https://github.com/dials/dials/commit/eff2f55415c2c17addd878587d2c28bff0c71389), we have to recalculate batch offsets held by `data_manager` after running `cosym`. We cannot simply swap experiment lists.

That is, we have to call `self._data_manager._set_batches()` after this:
https://github.com/xia2/xia2/blob/28e0bc80dc7c0181c67d26e61c99fac88c8cde5b/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py#L901-L910

Otherwise, we mess up batch IDs. If we are (un)lucky, the problem is manifested by
```
File "/prog/dials/modules/dials/src/dials/util/batch_handling.py", line 35, in _reduce
        assert len(set(reduced_batches)) == len(reduced_batches)
```
(i.e. duplicated batch numbers) but sometimes this leads to silent data corruption.

**Comment by amyjaynethompson** [comment]
Thank-you for bringing this to our attention - this has been addressed in PR#789 and merged in. Let us know if you still have any lingering issues.
