### ISSUE TITLE
This could be tidier (I mean the message)

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#80]
Autoindexing SWEEP1, SWEEP2, SWEEP3, SWEEP4, SWEEP5, SWEEP6, SWEEP7, SWEEP8, SWEEP9, SWEEP10, SWEEP11, SWEEP12 & SWEEP13

in xia2 output - if it said "Autoindexing SWEEP1 to 13" that would be *awesome* :)

**Comment by rjgildea** [comment]
Could be difficult - sweep name could be any arbitrary string - it is only by default that it is numbered SWEEP1...SWEEPN

**Comment by graeme-winter** [comment]
no arguments, however if it is the case that all strings start with SWEEP could make this happen yes?

**Comment by graeme-winter** [comment]
(I agree with prejudice that this is a trivial improvement)

**Comment by Anthchirp** [comment]
This will currently fall over when sweepnames have a prefix of "SWEEP" not followed by an integer.
