### ISSUE TITLE
 xia2/tests /regression/test_ssx.py on Windows

### ISSUE THREAD

**Issue by bwithd** [xia2/xia2#818]
it uses * directly in the file path which is not valid on Windows.
Error: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\tqt73344\\.cache\\dials_data\\cunir_serial\\merlin0047_1700*.cbf

**Comment by dagewa** [comment]
Should be fixed by #824, although it's not actually the same error that is fixed (I did not see the problem with `*`, but I did find other issues). Please re-open if problems are seen again
