### ISSUE TITLE
May be instructive to plot fraction of reflections indexed

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#86]
i.e. like

```
-------------------- Spotfinding SWEEP1 --------------------
236870 spots found on 360 images (max 5730 / bin)
*                                                           
*********                                                   
*******************                                         
***************************************                     
***********************************************            *
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                          360
```

except plot fraction indexed - can spot if indexing problems... have example (SBGrid 68 & 117) where xtal slipped so only subset of reflections indexed.

**Comment by rjgildea** [comment]
The DIALS html report does contain this information (well almost, it plots #strong and #indexed, so should be clear something may be amiss if they start diverging):
LogFiles/AUTOMATIC_DEFAULT_NATIVE_SWEEP1_INDEX.html
![screen shot 2016-11-14 at 10 24 07](https://cloud.githubusercontent.com/assets/2810624/20261161/93601524-aa54-11e6-956a-973bb281c752.png)

**Comment by graeme-winter** [comment]
![newplot 2](https://cloud.githubusercontent.com/assets/1241716/20261263/f17d8a10-aa54-11e6-9edd-947b6301a414.png)

OK, this is exactly what I wanted :)

**Comment by graeme-winter** [comment]
Can we ascii-art this to xia2 output? Seems important!

**Comment by graeme-winter** [comment]
Above is sbgrid 117: https://data.sbgrid.org/dataset/117/

Other examples exist...

**Comment by graeme-winter** [comment]
XDS missets

![missets-xds](https://cloud.githubusercontent.com/assets/1241716/20261690/d8dde868-aa56-11e6-8a63-b000b4e3d52b.png)

**Comment by graeme-winter** [comment]
@rjgildea how was is we tell xia2 to use local indexing rather than global? may make a real difference here...

**Comment by graeme-winter** [comment]
SBGrid 68

![newplot 3](https://cloud.githubusercontent.com/assets/1241716/20261882/af4bfac0-aa57-11e6-9a92-ebf79f812a1d.png)

**Comment by graeme-winter** [comment]
Completely different beamline (apparently...) one SSRL other NSLS...

**Comment by rjgildea** [comment]
```
$ cat index.phil
indexing.index_assignment.method=local
$ xia2 index.phil_file=index.phil [...]
```

**Comment by graeme-winter** [comment]
10-4 obliged

**Comment by graeme-winter** [comment]
Okey dokey - possible xia2 feature request then - given plots above switch on local indexing... was deal maker in example above!
