### ISSUE TITLE
10.15785/SBGRID/117 needs attention for xia2 -dials

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#9]
Running xia2 -dials gives poor results, running xia2 -3dii works very well => attention required for the former. Data from Pilatus detector (is cbf format) and has other issues.

**Comment by rjgildea** [comment]
Appears to be resolved by https://github.com/dials/dials/issues/122

`High resolution limit                   	  3.25	  8.82	  3.25
Low resolution limit                    	 97.93	 97.98	  3.31
Completeness                            	100.0	100.0	100.0
Multiplicity                            	 12.8	 11.8	 12.3
I/sigma                                 	 11.1	 31.9	  0.7
Rmerge(I)                               	0.140	0.042	3.624
Rmerge(I+/-)                            	0.137	0.042	3.533
Rmeas(I)                                	0.146	0.044	3.782
Rmeas(I+/-)                             	0.149	0.045	3.851
Rpim(I)                                 	0.041	0.013	1.074
Rpim(I+/-)                              	0.057	0.017	1.518
CC half                                 	0.997	0.996	0.504
Wilson B factor                         	0.000
Anomalous completeness                  	100.0	 99.9	  5.1
Anomalous multiplicity                  	  6.8	  6.7	  6.4
Anomalous correlation                   	-0.156	-0.310	-0.016
Anomalous slope                         	0.890	0.000	0.000
dF/F                                    	0.120
dI/s(dI)                                	1.117
Total observations                      	902432	45142	42346
Total unique                            	70303	3828	3448
Assuming spacegroup: P 41 2 2
Other likely alternatives are:
P 43 2 2
Unit cell:
196.827 196.827 225.793
90.000  90.000  90.000
`

**Comment by graeme-winter** [comment]
Good stuff :-)
