### ISSUE TITLE
absolute imports

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#97]
Opinions on moving xia2 to only use absolute imports ([PEP 328](https://www.python.org/dev/peps/pep-0328/))?

Essentially add
```
from __future__ import absolute_import
```
to every file and modify other import statements to use the full path, for example in Handlers/Streams/randomfile.py
```
import Debug
```
may need to become
```
import xia2.Handlers.Streams.Debug
```

Downside: Breaks compatibility with Python 2.4.
Upside: Eliminates 5 unnecessary file operations (dials/dials#288) for each new package import that is not in the current directory.
Upside 2: Brings us closer to Python 3 compatibility.

**Comment by rjgildea** [comment]
Pretty sure cctbx now only support Python 2.5 upwards anyway?

**Comment by Anthchirp** [comment]
[Yes, you are right. Bootstrap is the exception.](http://phenix-online.org/pipermail/cctbxbb/2016-September/001450.html)

**Comment by Anthchirp** [comment]
I just learned that ```import json``` is 2.6, so that answers this question for dials as well.

**Comment by rjgildea** [comment]
No objection to absolute imports (at least in principle).

**Comment by Anthchirp** [comment]
```
$ strace -c xia2
```
before patch:
7176 + 1875 = 9051 file not found errors
after patch:
6980 + 1826 = 8806 file not found errors
:+1:
