### ISSUE TITLE
html log files very slow on in-house firefox

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#98]
as discovered by Harry.
This is partially due to importing the javascript libraries multiple times. Loading them only once improves the loading times a bit, patch for this is on its way.

More can be gained by changing the data table layout and potentially reducing the number of data points. Particularly with 500px wide graphs (why?) having, say, 3600 points may not always be necessary.

**Comment by Anthchirp** [comment]
also look at ```/dls/mx-scratch/rjgildea/joint_refinement/tehA_dials/002/DEFAULT/analysis/multi-crystal-report.html```

**Comment by rjgildea** [comment]
Improvements made. Now faster, e.g.:
https://github.com/xia2/xia2/commit/726e47b0274732988915a9c6239450c5c235e30a
https://github.com/xia2/xia2/commit/4e754cbedcc53f3e4c0a3fa548bceab447dddf16
