### ISSUE TITLE
get_batch_to_dose exceptions

### ISSUE THREAD

**Issue by pameyer** [xia2/xia2#99]
First seen in xia2 0.5.161 (from DIALS 1.4.1), several datasets that previously processed failed with KeyError originating from get_batch_to_dose (appears related to https://github.com/xia2/xia2/commit/3f9c989f435013152abaf1e69741229d75799c55 , https://github.com/xia2/xia2/issues/90).  Same behavior seen for xia2 0.5.152/DIALS 1.4.0.  No apparent correlation with xia2 pipeline or input image format.

xia2.txt,xia2.error,xia2-debug.txt from example case [d76p3.zip](https://github.com/xia2/xia2/files/735947/d76p3.zip).

seen (and manually spot-checked) processing:
doi:10.15785/SBGRID/76
doi:10.15785/SBGRID/84
doi:10.15785/SBGRID/137
doi:10.15785/SBGRID/138
doi:10.15785/SBGRID/155
doi:10.15785/SBGRID/157
doi:10.15785/SBGRID/159
doi:10.15785/SBGRID/160

Haven't checked xia2 0.5.170/DIALS 1.4.2; but git history suggests those version would show the same problem.

**Comment by rjgildea** [comment]
Could you try with a recent nightly (development) build from http://dials.github.io/installation.html? I think this should be fixed in the recent nightly builds, and also in the version of DIALS 1.4.2 that CCP4 are distributing in update 28 (they have a patched version to fix a problem with epochs).

**Comment by rjgildea** [comment]
Confirmed for doi:10.15785/SBGRID/76 that this is:

a) broken in 1.4.2
b) fixed in latest nightly build
c) fixed in CCP4 7.0.28

Hopefully we'll get a version 1.4.3 out soon including the fix.

**Comment by pameyer** [comment]
@rjgildea - I've confirmed that it's fixed in the latest nightly for several others as well (some are still running).

Thanks for the quick turnaround!
